accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from accounts import views

urlpatterns = [
	url(r'^send_login_email$', views.send_login_email, name='send_login_email'),
	url(r'^login$', views.login, name='login'),
	url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.conf.urls import url, include
from lists import views as list_views
from lists import urls as list_urls
from accounts import urls as accounts_urls
from lists import api_urls
from lists.api import router

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^accounts/', include(accounts_urls)),
    #url(r'^api/', include(api_urls)),
    url(r'^api/', include(router.urls)),
]

accounts/models.py
import uuid

from django.contrib import auth
from django.db import models

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='shared_lists'
    )

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


    @property
    def name(self):
        return self.item_set.first().text


    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
	class Meta:
		model = Item
		fields = ('text',)
		widgets = {
			'text': forms.fields.TextInput(attrs={
				'placeholder': 'Enter a to-do item',
				'class': 'form-control input-lg',
			}),
		}
		error_messages = {
			'text': {'required': EMPTY_ITEM_ERROR}
		}


class NewListForm(ItemForm):
	def save(self, owner):
		if owner.is_authenticated:
			return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
		else:
			return List.create_new(first_item_text=self.cleaned_data['text'])


class ExistingListItemForm(ItemForm):
	def __init__(self, for_list, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.instance.list = for_list

	def validate_unique(self):
		try:
			self.instance.validate_unique()
		except ValidationError as e:
			e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
			self._update_errors(e)

accounts/views.py
from django.contrib import auth, messages
from django.core.mail import send_mail
from django.shortcuts import redirect

from accounts.models import Token

from django.core.urlresolvers import reverse


def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + '?token=' + str(token.uid)
    )

    message_body = 'Use this link to log in:\n\n{url}'.format(url=url)

    send_mail(
        'Your login link for Superlists',
        message_body,
        'damian.mozniak@o2.pl',
        [email]
    )
    messages.add_message(
        request,
        messages.SUCCESS,
        "Check your email, we've sent you a link you can use to log in."
    )
    return redirect('/')


def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect

from lists.forms import ItemForm, ExistingListItemForm
from lists.models import Item, List
from django.contrib.auth import get_user_model

User = get_user_model()
from lists.forms import ExistingListItemForm, ItemForm, NewListForm


def home_page(request):
	return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
	list_ = List.objects.get(id=list_id)
	form = ExistingListItemForm(for_list=list_)
	if request.method == 'POST':
		form = ExistingListItemForm(for_list=list_, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect(list_)

	return render(request, 'list.html', {'list': list_, "form": form})


def new_list(request):
	form = NewListForm(data=request.POST)
	if form.is_valid():
		list_ = form.save(owner=request.user)
		return redirect(list_)
	return render(request, 'home.html', {'form': form})


def my_lists(request, email):
	owner = User.objects.get(email=email)
	return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>

<body>
<div class="container">

    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Superlists</a>
            {% if user.email %}
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Logged in as {{ user.email }}</li>
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                </ul>
            {% else %}
                <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
                    <span>Enter email to log in:</span>
                    <input class="form-control" name="email" type="text"/>
                    {% csrf_token %}
                </form>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        <div class="row">
            <div class="col-md-8">
                {% for message in messages %}
                    {% if message.level_tag == 'success' %}
                        <div class="alert alert-success">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-warning">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
                {% block list_form %}
                    <form id="id_item_form" method="POST" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        <div class="form-group has-error">
                            <div class="help-block">
                                {% if form.errors %}
                                    {{ form.text.errors }}
                                {% endif %}
                            </div>
                        </div>
                    </form>
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block extra_content %}
            {% endblock %}
        </div>
    </div>
</div>

<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/list.js"></script>
{% block scripts %}
      <script>
$(document).ready(function () {
  window.Superlists.initialize();
});
      </script>
    {% endblock scripts %}

</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
    </table>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            window.Superlists.initialize({
                listApiUrl: "{% url 'list-detail' list.id %}",
                itemsApiUrl: "{% url 'item-list' %}",
                listId: {{ list.id }},
            });
        });
    </script>
{% endblock scripts %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}